version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ../:/usr/share/nginx/html
      - ./data/conf.d:/etc/nginx/conf.d
    network_mode: "bridge"