version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../:/usr/share/nginx/html
      - ./data/conf.d:/etc/nginx/conf.d
    privileged: true
    restart: always
    networks:
      - nginx-net

networks:
  nginx-net:
    driver: bridge
    ipam:
      driver: default