version: "3"
services:
  ipsec-vpn:
    image: hwdsl2/ipsec-vpn-server
    container_name: ipsec-vpn-server
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    volumes:
      - ./ipsec.d:/etc/ipsec.d
      - ./lib/modules:/lib/modules:ro
    privileged: true
    environment:
      VPN_IPSEC_PSK: "psk123456"
      VPN_USER: "user123456"
      VPN_PASSWORD: "pwd123456"
    restart: always
    network_mode: "bridge"