version: "3"
services:
  mysql:
    image: hwdsl2/ipsec-vpn-server
    container_name: ipsec-vpn-server
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    volumes:
      - ./ikev2-vpn-data:/etc/ipsec.d
      - ./lib/modules:/lib/modules:ro
    privileged: true
    environment:
      VPN_IPSEC_PSK: "vpn_user_psk"
      VPN_USER: "vpn_user"
      VPN_PASSWORD: "vpn_user_pwd"
    restart: always
    networks:
      - ipsec-net

networks:
  ipsec-net:
    driver: bridge
    ipam:
      driver: default