version: "3"
services:
  pptp:
    image: vimagick/pptp
    ports:
      - "1723:1723"
    environment:
      - SERVER=54.92.87.72 # 服务器的公网IP
      - TUNNEL=vps # VPN名称
      - USERNAME=username # 用户名
      - PASSWORD=password # 密码
    privileged: true
    restart: unless-stopped
#    restart: always
    network_mode: "host"